package com.resourceful_refinement.content.pug;

public enum LaunchpadFailureReason {
    NONE,
    INCOMPLETE_ASSEMBLY,
    WRONG_MODE,
    NO_CARGO,
    PUG_NOT_FULL,
    INCOMPLETE_DESTINATION_ADDRESS,
    DESTINATION_MISSING,
    DESTINATION_AMBIGUOUS,
    SOURCE_SKY_OBSTRUCTED,
    DESTINATION_SKY_OBSTRUCTED,
    INSUFFICIENT_FUEL,
    WAITING_FOR_REDSTONE,
    WAITING_FOR_TIMER,
    PAD_OCCUPIED
}
